package.json, src/typetalk.coffee
stop repeat updating access token except 401
=> stop repeat updating access token except 401

README.md, src/typetalk.coffee, test/typetalk.test.coffee
Typetalk changed top domain to .com from .in.
=> Use typetalk.com instead of typetalk.in

LICENSE
This pull request fixes copyright in LICENSE file for #12
=> Fix copyright

README.md
- Uses svg travis badge
https://travis-ci.org/nulab/hubot-typetalk
=> Use svg travis badge

README.md
=> Use svg npm badge

test/typetalk.test.coffee
=> Resolve warnings in unit test

README.md
- Uses svg badge for coverall status
=> Use svg coveralls badge

.travis.yml
=> Run linter in CI

.travis.yml
=> Report coverage

.npmignore
=> Updated npmignore

README.md
=> Updated coveralls URL

test/typetalk-streaming.test.js
=> Improve coverage

lib/typetalk-streaming.js, test/typetalk-streaming.test.js
=> Improved coverage

package-lock.json, package.json
No breaking changes
https://github.com/nickmerwin/node-coveralls/compare/3.0.3...master
=> Using coveralls 3.0.7

package-lock.json, package.json
https://github.com/StevenLooman/mocha-lcov-reporter/compare/0.0.1...1.3.0
=> Using mocha-lcov-reporter 1.3.0

package-lock.json, package.json
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md
https://github.com/mochajs/mocha/compare/v6.2.0...v6.2.2
=> Using mocha 6.2.2

.travis.yml, package-lock.json, package.json
https://nodejs.org/es/blog/npm/peer-dependencies/
=> Moved hubot to peerDependency

package-lock.json, package.json
https://github.com/eslint/eslint/blob/master/CHANGELOG.md
=> Using eslint 6.6.0

package-lock.json, package.json, test/typetalk-streaming.test.js
https://github.com/jashkenas/underscore/compare/1.6.0...1.9.1
=> Using underscore 1.9.1

package-lock.json, package.json
https://github.com/websockets/ws/releases
=> Using ws 7.2.0

lib/typetalk-streaming.js, package-lock.json, package.json, test/typetalk-streaming.test.js
latest ws library only allow ws or wss protocols.
=> Update ws library
